// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionMasViewCell : UICollectionViewCell
	{
		public CollectionMasViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
