// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionHomeOrdersViewCell : UICollectionViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CollectionHomeOrdersViewCell));


        public string lblOrders
        {
            get => labelOrders.Text;
            set => labelOrders.Text = value;

        }

        public UIImage BackgroundImage
        {
            get => imgBackGround.Image;

            set => imgBackGround.Image = value;


        }

        partial void btnOrders(NSObject sender)
        {

        }

		public CollectionHomeOrdersViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
