// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionHomeViewCell : UICollectionViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CollectionHomeViewCell));

        public string btnTitle
        {
            get => btnProfile.Title(UIControlState.Normal);
            set => btnProfile.SetTitle(value, UIControlState.Normal);

        }

        public UIImage BackgroundImage
        {
            get => imgBackground.Image;

            set => imgBackground.Image = value;


        }


		public CollectionHomeViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
