// This file has been autogenerated from a class added in the UI designer.

using System;
using Drinkify.Helper;
using Foundation;
using Patxi.Models;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionCheckOutCell : UICollectionViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CollectionCheckOutCell));

        public string txtCantidad
        {
            get => txtCant.Text;
            set => txtCant.Text = value;

        }

        public string lblNombre
        {
            get => lblTitle.Text;
            set => lblTitle.Text = value;

        }

        public string lblTotalPrice
        {
            get => lblTotal.Text;
            set => lblTotal.Text = value;

        }

		public override void LayoutSubviews()
		{
            base.LayoutSubviews();
            txtCant.EditingDidEnd+= delegate {
                foreach (Producto item in DataPersistanceClass.products)
                {
                    if(item.Name==lblNombre){
                        item.ItemsBought = txtCant.Text;
                    }
                }
            };

		}

		public CollectionCheckOutCell (IntPtr handle) : base (handle)
		{
		}
	}
}
