// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionBebidaViewCell : UICollectionViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CollectionBebidaViewCell));


        public string btnTitle
        {
            get => btnPrincipal.Title(UIControlState.Normal);
            set => btnPrincipal.SetTitle(value,UIControlState.Normal);

        }

        public UIImage BackgroundImage
        {
            get => imgFondo.Image;

            set => imgFondo.Image = value;


        }
		public CollectionBebidaViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
