// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class CollectionBotanaViewCell : UICollectionViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CollectionBotanaViewCell));


        public string btnTitle
        {
            get => btnBotanas.Title(UIControlState.Normal);
            set => btnBotanas.SetTitle(value, UIControlState.Normal);

        }

        public UIImage BackgroundImage
        {
            get => imgBackGround.Image;

            set => imgBackGround.Image = value;


        }


		public CollectionBotanaViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
