// This file has been autogenerated from a class added in the UI designer.

using System;
using Firebase.Database;
using Foundation;
using Patxi.Models;
using UIKit;

namespace Drinkify.Storyboards
{
    public partial class BebidasViewController : UIViewController, IUICollectionViewDataSource, IUICollectionViewDelegate, IUICollectionViewDelegateFlowLayout
	{
        NSDictionary bebidasDic;
		public BebidasViewController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            collectionView.Delegate = this;
            collectionView.DataSource = this;

            DatabaseReference rootNode = Database.DefaultInstance.GetRootReference();
            //nuint quantity;
            DatabaseReference bebidas = rootNode.GetChild("0").GetChild("Productos").GetChild("Bebidas");
            bebidas.ObserveSingleEvent(DataEventType.Value, (snapshot) => {
                if (!snapshot.Exists)
                    return;

                bebidasDic = snapshot.GetValue<NSDictionary>();
                collectionView.ReloadData();

            }, (error) => {
                Console.WriteLine(error.LocalizedDescription);
            });



        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {

            if (segue.Identifier.Equals("detalleBebidasSegue")==true){

                var vc = segue.DestinationViewController as DetalleViewController;
                vc.isOrders = false;
                vc.isBebidas = true;
                vc.isBotanas = false;
                var btn = sender as UIButton;
                NSObject objectOut;
                bebidasDic.TryGetValue(NSObject.FromObject(btn.CurrentTitle),out objectOut);
                var dasd = objectOut as NSDictionary;
                vc.diccionary = dasd??bebidasDic;


            }

        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            try
            {
                return bebidasDic.Keys.Length;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return 10;
            }

        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = collectionView.DequeueReusableCell(CollectionBebidaViewCell.Key, indexPath) as CollectionBebidaViewCell;


            var length = collectionView.VisibleCells.Length;
            var title = (Alcoholes) (int)indexPath.Item;
            UIImage img;



            switch (indexPath.Item)
            {
                case 0:
                    img = UIImage.FromBundle("Brandy");
                    break;
                case 1:
                    img = UIImage.FromBundle("Cerveza");
                    break;
                case 2:
                    img = UIImage.FromBundle("Cognac");
                    break;
                case 3:
                    img = UIImage.FromBundle("Ginebra");
                    break;
                case 4:
                    img = UIImage.FromBundle("Mezcal");
                    break;
                case 5:
                    img = UIImage.FromBundle("ron");
                    break;
                case 6:
                    img = UIImage.FromBundle("Tequila");
                    break;
                case 7:
                    img = UIImage.FromBundle("Vino");
                    break;
                case 8:
                    img = UIImage.FromBundle("Vodka");
                    break;
                case 9:
                    img = UIImage.FromBundle("Whisky");
                    break;
                
                default:
                    img = new UIImage();
                    break;
            }

            cell.BackgroundImage = img;
            cell.btnTitle = title.ToString();

            return cell;
                
        }



        [Export("numberOfSectionsInCollectionView:")]
        public nint NumberOfSections(UICollectionView collectionView)
        {
            return 1;
        }

        [Export("collectionView:layout:minimumLineSpacingForSectionAtIndex:")]
        public nfloat GetMinimumLineSpacingForSection(UICollectionView collectionView, UICollectionViewLayout layout, nint section)
        {
            return 15;
        }


    }
}
