// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
    public partial class BebidasViewController : UIViewController, IUICollectionViewDataSource, IUICollectionViewDelegate, IUICollectionViewDelegateFlowLayout
	{
		public BebidasViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {

            if (segue.Identifier.Equals("detalleSegue")==true){

                var vc = segue.DestinationViewController as DetalleViewController;
            }else if (segue.Identifier.Equals("prueba") == true)
            {
                var vc = segue.DestinationViewController as DetalleViewController;
            }

        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return 1;
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = collectionView.DequeueReusableCell(CollectionBebidaViewCell.Key, indexPath) as CollectionBebidaViewCell;

            cell.btnTitle = "Tequila";

            return cell;
        }
    }
}
