// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using Patxi.Models;
using UIKit;

namespace Drinkify.Storyboards
{
    public partial class DetalleViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate
	{

        List<Producto> Productos = new List<Producto>();
        int contador = 0;

		public DetalleViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            CatalogTableView.DataSource = this;
            CatalogTableView.Delegate = this;

            btnRegresar.Clicked += delegate {
                DismissViewController(true, null);
            };

            btnCheckOut.Clicked += delegate {
                //TODO: enviar a pantalla de checkOut

            };
        }

        public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("TableCell", indexPath) as TableCatalogViewCell;
            cell.NameText = "Jose Cuervo Rolling Stones";
            cell.PriceText = "$260.00";
            cell.QuantityText = "1 l";
            cell.DescriptionText = "Tequila Cuervo Tradicional Plata Rolling Stones";
            //cell.ProductImage = UIImage.FromBundle("Tequila1");
            return cell;
        }

        [Export("numberOfSectionsInTableView:")]
        public nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        public nint RowsInSection(UITableView tableView, nint section)
        {
            return 1;
            //return Productos.Count;
        }
	}
}
