// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class PatxiTrackerViewController : UIViewController
	{
		public PatxiTrackerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
