// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Drinkify.Storyboards
{
	public partial class ProfileViewController : UIViewController
	{
        
		public ProfileViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            imProfile.Image = UIImage.FromBundle("profileTest");

            btnBack.Clicked += delegate {
                DismissViewController(true, null);
            };

        }
	}
}
